=== thapaShrek/Gift-Card-Store/catalog_20049044.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">


    <xs:element name="gift_vouch">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Navigation" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="storelogo" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="main" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="footer" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Navigation">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="store_name"/>
                <xs:element ref="Content" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="main">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="category" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
            
        </xs:complexType>
    </xs:element>

    <xs:element name="category">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gift_card" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="kind" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="gift_card">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Data_Info"/>     
                <xs:element ref="card_list"/>          
            </xs:sequence>  
            <xs:attribute ref="GID" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Data_Info">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Name"/>
                <xs:element ref="Item_Num"/>
                <xs:element ref="type" />
                <xs:element ref="UID" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="Developer"/>
                <xs:element ref="Publisher" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="Amount"/>
                <xs:element ref="Validity"/>
                <xs:element ref="discount" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="cashback" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="Use_Place"/>
                <xs:element ref="Delievery" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="deli_type" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="Num_Users"/>
                <xs:element ref="Payment"/>
                <xs:element ref="policy"/>
                <xs:element ref="Availability"/>
                <xs:element ref="click"/>
            </xs:sequence>
            <xs:attribute ref="char" use="optional"/>
            <xs:attribute ref="platform" use="optional"/>
            <xs:attribute ref="currency" use="optional"/>
            <xs:attribute ref="class" use="optional"/>
            <xs:attribute ref="form" use="required"/>

        </xs:complexType>
    </xs:element>

    <xs:element name="card_list">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="card"/>
            </xs:sequence>
            <xs:attribute ref="CID"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="card">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="detail"/>
                <xs:element ref="card_detail"/>
            </xs:sequence>
            <xs:attribute ref="CID" />
        </xs:complexType>
    </xs:element>

    <xs:element name="detail">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="description"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="card_detail">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Quantity"/>
                <xs:element ref="Rating"/>
                <xs:element ref="Ranks"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Quantity">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Number"/>
                <xs:element ref="Title"/>
            </xs:sequence>
            <xs:attribute ref="location"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Rating">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Num"/>
                <xs:element ref="title"/>
            </xs:sequence>
            <xs:attribute ref="location"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Ranks">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Val"/>
                <xs:element ref="rank"/>
            </xs:sequence>
            <xs:attribute ref="location"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Delievery">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="deli_time" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Payment">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pay_phy" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="pay_eg" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="policy">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="return"/>
                <xs:element ref="refund"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="footer">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="address"/>
                <xs:element ref="contact"/>
                <xs:element ref="web_address"/>
                <xs:element ref="logo"/>
                <xs:element ref="branch"/>
                <xs:element ref="bar_code"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="address">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="street"/>
                <xs:element ref="city"/>
                <xs:element ref="postal_code" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="contact">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Phone"/>
                <xs:element ref="email"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="branch">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="st_location"/>
                <xs:element ref="st_contact"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="type">
        <xs:complexType mixed="true">
            <xs:attribute ref="form"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="Developer">
        <xs:complexType mixed="true">
            <xs:attribute ref="platform"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="Amount">
        <xs:complexType mixed="true">
            <xs:attribute ref="currency"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Validity">
        <xs:complexType mixed="true">
            <xs:attribute ref="char"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="click">
        <xs:complexType mixed="true">
            <xs:attribute ref="class"/>
        </xs:complexType>
    </xs:element>


    
    <xs:element name="storelogo"/>
    <xs:element name="store_name" type="xs:string"/>
    <xs:element name="Content" type="xs:string"/>
    <xs:element name="heading" type="xs:string"/>
    <xs:element name="Name" type="xs:string"/>
    <xs:element name="UID" type="xs:string"/>
    <xs:element name="description" type="xs:string"/>
    <xs:element name="Publisher" type="xs:string"/>
    <xs:element name="deli_type" type="xs:string" />
    <xs:element name="discount" type="xs:integer"/>
    <xs:element name="cashback" type="xs:integer"/>
    <xs:element name="Use_Place" type="xs:string"/>
    <xs:element name="deli_time" type="xs:string"/>
    <xs:element name="Num_Users" type="xs:integer"/>
    <xs:element name="Number" type="xs:integer"/>
    <xs:element name="Title" type="xs:string"/>
    <xs:element name="pay_phy" type="xs:string"/>
    <xs:element name="pay_eg" type="xs:string"/>
    <xs:element name="return" type="xs:string"/>
    <xs:element name="refund" type="xs:string"/>
    <xs:element name="Item_Num" type="xs:integer"/>
    <xs:element name="Availability" type="xs:string"/>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="Num" type="xs:decimal"/>
    <xs:element name="title" type="xs:string"/>
    <xs:element name="Val" type="xs:string"/>
    <xs:element name="rank" type="xs:string"/>
    <xs:element name="street" type="xs:string"/>
    <xs:element name="city" type="xs:string"/>
    <xs:element name="postal_code" type="xs:string"/>
    <xs:element name="Phone" type="xs:integer"/>

    <xs:element name="st_location" type="xs:string"/>
    <xs:element name="st_contact" type="xs:integer"/>
    <xs:element name="web_address" type="xs:string"/>
    <xs:element name="bar_code"/>
    <xs:element name="logo"/>
    

    <xs:attribute name="SID" type="xs:ID"/>
    <xs:attribute name="CID" type="xs:ID"/>
    <xs:attribute name="GID" type="xs:string"/>
    <xs:attribute name="form">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Physical"/>
                <xs:enumeration value="Digital"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="platform">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="e-commerce"/>
                <xs:enumeration value="Food"/>
                <xs:enumeration value="Music"/>
                <xs:enumeration value="Retail Store"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="kind" type="xs:string"/>
    <xs:attribute name="currency" type="xs:string"/>
    <xs:attribute name="char" type="xs:string"/>
    <xs:attribute name="location" type="xs:string"/>
    <xs:attribute name="class" type="xs:string"/>
    
    <xs:element name="email">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[^@]+@[^\.]+\..+"/>
            </xs:restriction>
        </xs:simpleType>

    </xs:element>

</xs:schema>

=== thapaShrek/Gift-Card-Store/catalog_20049044.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type="text/css" href="catalog_20049044.css"?>

<gift_vouch xsi:noNamespaceSchemaLocation="catalog_20049044.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    
    <Navigation >
        <store_name >  Smiles for Miles </store_name>
        <Content>Home</Content>
        <Content>Products</Content>
        <Content>About Us</Content>
        <Content>Contact</Content>
    </Navigation>
    
    <storelogo/>
    <main>
        <category kind="store">
            
            <gift_card GID="2a">
                <Data_Info form="Digital">
                    <Name>Amazon Gift Card</Name>
                    <Item_Num>102259815</Item_Num>
                    <type form="Digital">Digital</type>
                    <UID>4515555544</UID>
                    
                    <Developer platform="e-commerce">Amazon</Developer>
                    <Publisher>Amazon.com </Publisher>
                    <Amount currency="pound"> price</Amount>
                    <Validity char="date">2022-10-15</Validity>
                    <discount>5</discount>
                    <Use_Place>Amazon App or Website</Use_Place>  
                    <Delievery>
                        <deli_time>Instant Delievery</deli_time>
                        <deli_time>In the future</deli_time>
                    </Delievery> <!-- Optional Data-->
                    <deli_type>Text Message or Email</deli_type>
                    <Num_Users>6</Num_Users>
                    <Payment>
                        <pay_eg>e-sewa, Khalti</pay_eg>
                    </Payment>
                    <policy>
                        <return>No</return>
                        <refund>Yes</refund>
                    </policy>
                    <Availability>Yes</Availability>
                    <click class="button">Add to Cart</click> 
                </Data_Info>
                <card_list>
                    <card CID="G1">
                        <detail>
                            <name>Amazon</name>
                            <description>Amazon is an online-shopping company. The gift card can be used to get
                                discounts when ordering from amazon.</description>
                        </detail>
                        <card_detail>
                            <Quantity location="bottom">
                                <Number>50</Number>
                                <Title>Quantity</Title>
                            </Quantity>
                            <Rating location="bottom">
                                <Num>4.5</Num>
                                <title>Rating</title>
                            </Rating>
                            <Ranks location="bottom">
                                <Val>#1</Val>
                                <rank>Rank</rank>
                            </Ranks>
                        </card_detail>
                    </card>
                </card_list>
            </gift_card>
            <gift_card GID="2b">
                <Data_Info form="Physical">
                    <Name> Sainsbury Gift Card</Name>
                    <Item_Num>154193735</Item_Num>
                    <type form="Physical">Physical</type>
                    
                    <Developer platform="Retail Store">Sainsbury's</Developer>
                    <Publisher>Sainbury</Publisher>
                    <Amount currency="pound"> 25</Amount>
                    <Validity char="date">2022-12-27</Validity>
                    <cashback>3</cashback>
                    <Use_Place>Any retail stores or gas stations</Use_Place>  
                    <Delievery>
                        <deli_time>Instant Delievery</deli_time>
                    </Delievery> 
                    <Num_Users>1</Num_Users>
                        
                    <Payment>
                        <pay_phy>Cash on Delievery</pay_phy><!-- -->
                        <pay_eg>e-sewa, Khalti</pay_eg>
                    </Payment>
                    <policy>
                        <return>no</return>
                        <refund>no</refund>         
                    </policy>
                       
                    <Availability>Yes</Availability>
                    <click class="button"> Add to Cart</click>
                </Data_Info>
                <card_list>
                    <card CID="G2">
                        <detail>
                            <name>Sainsbury</name>
                            <description>Sainsbury is a retail store located in the UK. The gift card can be used to get
                                discounts when shopping from Sainsbury.</description>
                        </detail>
                        <card_detail>
                            <Quantity location="bottom">
                                <Number>25</Number>
                                <Title>Quantity</Title>
                            </Quantity>
                            <Rating location="bottom">
                                <Num>4.1</Num>
                                <title>Rating</title>
                            </Rating>
                            <Ranks location="bottom">
                                <Val>#11</Val>
                                <rank>Rank</rank>
                            </Ranks>
                        </card_detail>
                    </card>
                </card_list>
            </gift_card>
        </category>
        <category kind="Music">
                <gift_card GID="2c">
                    <Data_Info form="Digital">
                        <Name>Spotify Gift Card</Name>
                        <Item_Num> 152752415</Item_Num>

                        <type form="Digital">Digital</type>
                        <Developer platform="Music">Spotify</Developer>
                        
                        <Amount currency="pound">30</Amount>
                        <Validity char="date">2023-03-10</Validity>
                        <Use_Place>Spotify App or Website</Use_Place>  
                        <Delievery>
                            <deli_time>Instant Delievery</deli_time>
                            <deli_time>In the future</deli_time>
                        </Delievery> <!-- Optional Data-->
                        <deli_type>Your Phone Number or E-mail</deli_type>
                        <Num_Users>3</Num_Users>
                        <Payment>
                            <pay_eg>e-sewa, Khalti</pay_eg>
                        </Payment>
                        <policy>
                            <return>Yes</return>
                            <refund>No</refund>
                        </policy>
                        <Availability>Yes</Availability>
                        <click class="button"> Add to Cart</click>

                    </Data_Info>
                    <card_list>
                        <card CID="G3">
                            <detail>
                                <name>Spotify</name>
                                <description>Spotify is an online music streaming company. The gift card can be used to get
                                    offers when creating new accounts in spotify.</description>
                            </detail>
                            <card_detail>
                                <Quantity location="bottom">
                                    <Number>100</Number>
                                    <Title>Quantity</Title>
                                </Quantity>
                                <Rating location="bottom">
                                    <Num>4.8</Num>
                                    <title>Rating</title>
                                </Rating>
                                <Ranks location="bottom">
                                    <Val>#3</Val>
                                    <rank>Rank</rank>
                                </Ranks>
                            </card_detail>
                        </card>
                    </card_list>
                </gift_card>
                <gift_card GID="2d">
                    <Data_Info form="Digital">
                        <Name>iTunes Gift Card</Name>
                        <Item_Num>178992547</Item_Num>
                        <type form="Digital">Digital</type>
                        <Developer platform="Music">Apple</Developer>
                        <Amount currency="pound">100</Amount>
                        <Validity char="date">2022-09-01</Validity>
                        <Use_Place>itunes App or website</Use_Place>  
                        <Delievery>
                            <deli_time>Instant Delievery</deli_time>
                            <deli_time>In the future</deli_time>
                        </Delievery> <!-- Optional Data-->
                        <deli_type>Text Message or E-mail</deli_type>
                        <Num_Users>3</Num_Users>
                        <Payment>
                            <pay_eg>e-sewa, Khalti</pay_eg>
                        </Payment>
                        <policy>
                            <return>No</return>
                            <refund>No</refund>
                        </policy>
                        <Availability>No</Availability>
                        <click class="button"> Add to Cart</click>

                    </Data_Info>
                    <card_list>
                        <card CID="G4">
                            <detail>
                                <name>iTunes</name>
                                <description>itunes is a software program created by the Apple company that
                                    acts as a media player and media library. The gift card can be used to get
                                    discounts when purchasing music.</description>
                            </detail>
